Что такое вектор?

- В школьной геометрии — направленный отрезок.
- В линейной алгебре — элемент векторного пространства.
- В Python — числовой массив (например, одномерный массив NumPy).

Вектор — это набор чисел, записанных в определенном порядке, например, в столбик или в строчку.

 В Python мы представляем вектор как одномерный массив NumPy, так как он может быть создан из списка чисел. То есть вектор сам по себе обретает смысл в зависимости от контекста.
 
Основные характеристики вектора
У вектора есть две главных характеристики: координаты и размерность.

- *Координаты вектора* — это числа, из которых он состоит. 

- *Размерность вектора* — это количество координат.

Например, для вектора количества лайков координаты — это числа 23, 78, 65 и 90, а его размерность равна 4.


## Базовые операции над векторами

### Сложение и вычитание векторов
Сложение векторов происходит поэлементно, складываем или вычитаем элементы с одинаковым индексом.
 Python происходит при помощи знаков + и -. Важно, задать векторы именно как массивы NumPy, а не как обычные списки типа list. 
 Складывать и вычитать можно только матрицы одинакового размера
  




In [1]:
import numpy as np
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print (a+b)

[15 23 14  8]


## Умножение вектора на число
Это тоже происходит поэлементно, то есть каждая координата вектора умножается на число.


In [2]:
import numpy as np
a = np.array([10, 8, 5, 1])
print(a*2)

[20 16 10  2]


In [3]:
import numpy as np
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a +b)
print(a-b)
print(a*2)

[15 23 14  8]
[ 5 -7 -4 -6]
[20 16 10  2]


## Матрицы. Основные понятия
**Матрица** — набор чисел, расположенных по строкам и столбцам, как в таблице.


In [5]:
import numpy as np
A = np.array([[1,-5,3],[2,2,1],[0,3,1],[2,4,12]])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [6]:
A.shape

(4, 3)

In [8]:
print("a_23 = ", A[1,2],"; a_32 = ", A[2,1])

a_23 =  1 ; a_32 =  3


In [9]:
B = np.matrix("1,-5;2,2;0,3")
B


matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [10]:
C = np.matrix("3,-1;2,6;4,0")
C

matrix([[ 3, -1],
        [ 2,  6],
        [ 4,  0]])

In [11]:
B+C

matrix([[ 4, -6],
        [ 4,  8],
        [ 4,  3]])

In [19]:
C*5

matrix([[15, -5],
        [10, 30],
        [20,  0]])

In [13]:
B

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [14]:
B.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

In [15]:
V = np.array([7,5,1])
V

array([7, 5, 1])

In [17]:
V.T

array([7, 5, 1])

In [18]:
A_1 = np.matrix("1,-5;2,2;0,3")
A_1

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

Умножить две матрицы можно только в том случае, если число столбцов в одной матрице равно числу строк во второй.

In [21]:
A_2 = np.matrix("3,1,0;-1,0,2")
A_2

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [22]:
np.dot(A_1,A_2)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [23]:
np.dot(A_2,A_1)

matrix([[  5, -13],
        [ -1,  11]])

In [8]:
#Тест для самопроверки
import numpy as np
A = np.array([[1,5,3],[2,2,1],[4,3,1],[2,4,12]])
B = np.array([[3,6,2],[6,7,3],[5,5,9],[8,4,1]])
Enemy = np.array([[2,9,1],[3,5,4],[6,3,10],[4,6,7]])
Power = np.array([2,2,2])
ArmySum = A + B
Warriors = ArmySum - Enemy
Result = np.dot(Warriors,Power)
print(Result)

[[ 4  4  8]
 [10  8  0]
 [ 6 10  0]
 [12  4 12]]
